//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkProjekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predmet
    {
        public int PredmetID { get; set; }
        public string NaizvPredmeta { get; set; }
        public int SmerID { get; set; }
    
        public virtual Smer Smer { get; set; }
    }
}
